# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ThatScotDataSci
email: alan@thatscotdatasci.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of professional data nerd Alan Clark
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thatscotdatasci.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: thatscotdatasci
twitter_url: https://twitter.com/thatscotdatasci

github_username:  thatscotdatasci
github_url: https://github.com/thatscotdatasci
repository: thatscotdatasci/thatscotdatasci.github.io # GitHub repository for this site

linkedin_url: https://www.linkedin.com/in/thatscotdatasci
stack_overflow_url: https://stackoverflow.com/users/9502131/thatscotdatasci?tab=profile

google_analytics: UA-116667042-1

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-github-metadata

# User defined collections
collections:
  wiki:
    output: true
  career:
    output: false

defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: default
      permalink: /:collection/:path

# Exclude from processing.
# The following items will not be processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
