name: Monthly Build

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    name: Create and push empty commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create an empty commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "Committing with comment: Monthly build - ${{ github.event.comment.created_at }}"
        git commit -m "Monthly build - ${{ github.event.comment.created_at }}" --allow-empty
    - name: Push empty commit
      run: |
        echo "Pushing to: github.com/${{ github.repository }}.git"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_REPO_TOKEN }}@github.com/${{ github.repository }}.git" master
